using System;


namespace CguessingGame
{
    class Program
    {
        static void Main(string[] args)
        {
            string difficulty;

            Console.WriteLine("What difficulty would you like? easy, medium or hard");
            difficulty = Console.ReadLine().ToLower();

// Initial values are set for the guess limit, chances left and amount of guesses taken, these values are modified in different blocks to suit the task
// for when the user chooses to play either easy, medium or hard. The random number is also generated by the program so the user has to guess differently everytime.

            
            int guess_limit = 12;
            int chances_left = 12;
            int guess_taken = 0;
            int guess;

            while (difficulty == "easy")
            {
                try
                {
                    Random rnd = new Random();
                    int random_number = rnd.Next(1, 11);
                    Console.Write("Enter a number between 1 - 10: ");
                    guess = int.Parse(Console.ReadLine());
                    guess_taken += 1;
                    chances_left -=2;
                    Console.WriteLine("You have " + chances_left/2 + " guesses left");
                    if (random_number == guess)
                    {
                        Console.WriteLine("You got it right");
                        break;  
                    }
                    else if (guess_taken == guess_limit/2)
                    {
                        Console.WriteLine("Game Over");
                        break;
                    }
                    else
                    {
                        Console.WriteLine("That was wrong");                   
                    }
                }
                catch (System.Exception)
                {
                    Console.WriteLine("Only numbers are allowed");
                }   
            }

            while (difficulty == "medium")
            {
                try
                {
                    Random rnd = new Random();
                    int random_number = rnd.Next(1, 21);
                    Console.Write("Enter a number between 1 - 20: ");
                    guess = int.Parse(Console.ReadLine());
                    guess_taken += 1;
                    chances_left -=3;
                    Console.WriteLine("You have " + chances_left/3 + " guesses left");
                    if (random_number == guess)
                    {
                        Console.WriteLine("You got it right");
                        break;  
                    }
                    else if (guess_taken == guess_limit/3)
                    {
                        Console.WriteLine("Game Over");
                        break;
                    }
                    else
                    {
                        Console.WriteLine("That was wrong");                   
                    }
                }
                catch (System.Exception)
                {
                    Console.WriteLine("Only numbers are allowed");
                }   
            }

            while (difficulty == "hard")
            {
                try
                {
                    Random rnd = new Random();
                    int random_number = rnd.Next(1, 51);
                    Console.Write("Enter a number between 1 - 50: ");
                    guess = int.Parse(Console.ReadLine());
                    guess_taken += 1;
                    chances_left -=4;
                    Console.WriteLine("You have " + chances_left/4 + " guesses left");
                    if (random_number == guess)
                    {
                        Console.WriteLine("You got it right");
                        break;  
                    }
                    else if (guess_taken == guess_limit/4)
                    {
                        Console.WriteLine("Game Over");
                        break;
                    }
                    else
                    {
                        Console.WriteLine("That was wrong");                   
                    }
                }
                catch (System.Exception)
                {
                    Console.WriteLine("Only numbers are allowed");
                }   
            }          
        
        }
    }
}
